"""
Topup order model for balance top-up requests.
"""
from sqlalchemy import BigInteger, Column, DateTime, Enum, String, Text
from sqlalchemy.sql import func

from src.database.models.base import Base
from src.database.models.enums import TopupStatus


class TopupOrder(Base):
    """Topup order model — one row per customer top-up request."""

    __tablename__ = "topup_orders"

    id = Column(String, primary_key=True)  # "TU" + 8-char hex, generated by service
    user_id = Column(BigInteger, nullable=False)  # Telegram user ID
    bot_user_id = Column(String, nullable=False)  # FK to bot_users.id (enforced in migration)
    amount = Column(BigInteger, nullable=False)  # Requested top-up amount in VND

    status = Column(
        Enum(TopupStatus, native_enum=False),
        default=TopupStatus.PENDING,
        nullable=False,
    )

    # Payment tracking (mirrors Order payment fields)
    payment_provider = Column(String, nullable=True)  # "payos" | "balance"
    payment_transaction_id = Column(String, nullable=True)
    payment_message_ids = Column(Text, nullable=True)  # JSON list of Telegram message IDs

    # PayOS fields
    payos_order_code = Column(BigInteger, nullable=True, unique=True)
    payos_payment_link_id = Column(String, nullable=True)
    payos_checkout_url = Column(Text, nullable=True)
    payos_qr_code = Column(Text, nullable=True)  # PayOS VietQR EMV payload

    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)
